### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by sharon-indegy** [unaPoloGTIc/trex-pam#4]
Per push:
1. build.
1. run unit-tests.
1. build Docker image.
1. run login tests on image.
1. push image to dockerhub.

**Comment by unaPoloGTIc** [comment]
Added action to build on push.
Wasteful process, to be improved.
(tests to be added)

**Comment by unaPoloGTIc** [comment]
Added action to push the dev/demo container to dockerhub on pushes to master if tests pass.
